// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: publishclient/publishapi/protos/publisher.proto

package publishapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCodes int32

const (
	ErrCodes_Unexpected   ErrCodes = 0
	ErrCodes_NotFound     ErrCodes = 1
	ErrCodes_AccessDenied ErrCodes = 2
	ErrCodes_UriNotUnique ErrCodes = 3
	ErrCodes_ErrorOffset  ErrCodes = 1100
)

// Enum value maps for ErrCodes.
var (
	ErrCodes_name = map[int32]string{
		0:    "Unexpected",
		1:    "NotFound",
		2:    "AccessDenied",
		3:    "UriNotUnique",
		1100: "ErrorOffset",
	}
	ErrCodes_value = map[string]int32{
		"Unexpected":   0,
		"NotFound":     1,
		"AccessDenied": 2,
		"UriNotUnique": 3,
		"ErrorOffset":  1100,
	}
)

func (x ErrCodes) Enum() *ErrCodes {
	p := new(ErrCodes)
	*p = x
	return p
}

func (x ErrCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_publishclient_publishapi_protos_publisher_proto_enumTypes[0].Descriptor()
}

func (ErrCodes) Type() protoreflect.EnumType {
	return &file_publishclient_publishapi_protos_publisher_proto_enumTypes[0]
}

func (x ErrCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCodes.Descriptor instead.
func (ErrCodes) EnumDescriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{0}
}

type PublishStatus int32

const (
	// PublishStatusCreated means publish is created but not uploaded yet
	PublishStatus_PublishStatusCreated PublishStatus = 0
	// PublishStatusCreated means publish is active
	PublishStatus_PublishStatusPublished PublishStatus = 1
)

// Enum value maps for PublishStatus.
var (
	PublishStatus_name = map[int32]string{
		0: "PublishStatusCreated",
		1: "PublishStatusPublished",
	}
	PublishStatus_value = map[string]int32{
		"PublishStatusCreated":   0,
		"PublishStatusPublished": 1,
	}
)

func (x PublishStatus) Enum() *PublishStatus {
	p := new(PublishStatus)
	*p = x
	return p
}

func (x PublishStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_publishclient_publishapi_protos_publisher_proto_enumTypes[1].Descriptor()
}

func (PublishStatus) Type() protoreflect.EnumType {
	return &file_publishclient_publishapi_protos_publisher_proto_enumTypes[1]
}

func (x PublishStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishStatus.Descriptor instead.
func (PublishStatus) EnumDescriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{1}
}

type ResolveUriRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveUriRequest) Reset() {
	*x = ResolveUriRequest{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveUriRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUriRequest) ProtoMessage() {}

func (x *ResolveUriRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUriRequest.ProtoReflect.Descriptor instead.
func (*ResolveUriRequest) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveUriRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type ResolveUriResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publish       *Publish               `protobuf:"bytes,1,opt,name=publish,proto3" json:"publish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveUriResponse) Reset() {
	*x = ResolveUriResponse{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveUriResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUriResponse) ProtoMessage() {}

func (x *ResolveUriResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUriResponse.ProtoReflect.Descriptor instead.
func (*ResolveUriResponse) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveUriResponse) GetPublish() *Publish {
	if x != nil {
		return x.Publish
	}
	return nil
}

type Publish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=objectId,proto3" json:"objectId,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Status        PublishStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=client.PublishStatus" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publish) Reset() {
	*x = Publish{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish) ProtoMessage() {}

func (x *Publish) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish.ProtoReflect.Descriptor instead.
func (*Publish) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{2}
}

func (x *Publish) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Publish) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Publish) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Publish) GetStatus() PublishStatus {
	if x != nil {
		return x.Status
	}
	return PublishStatus_PublishStatusCreated
}

func (x *Publish) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Publish) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Publish) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ok) Reset() {
	*x = Ok{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{3}
}

type GetPublishStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=objectId,proto3" json:"objectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishStatusRequest) Reset() {
	*x = GetPublishStatusRequest{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishStatusRequest) ProtoMessage() {}

func (x *GetPublishStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPublishStatusRequest) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{4}
}

func (x *GetPublishStatusRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *GetPublishStatusRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type GetPublishStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publish       *Publish               `protobuf:"bytes,1,opt,name=publish,proto3" json:"publish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishStatusResponse) Reset() {
	*x = GetPublishStatusResponse{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishStatusResponse) ProtoMessage() {}

func (x *GetPublishStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPublishStatusResponse) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{5}
}

func (x *GetPublishStatusResponse) GetPublish() *Publish {
	if x != nil {
		return x.Publish
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=objectId,proto3" json:"objectId,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Backlinks     []string               `protobuf:"bytes,5,rep,name=backlinks,proto3" json:"backlinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{6}
}

func (x *PublishRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *PublishRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *PublishRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *PublishRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PublishRequest) GetBacklinks() []string {
	if x != nil {
		return x.Backlinks
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=uploadUrl,proto3" json:"uploadUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{7}
}

func (x *PublishResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

type UnPublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=objectId,proto3" json:"objectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnPublishRequest) Reset() {
	*x = UnPublishRequest{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnPublishRequest) ProtoMessage() {}

func (x *UnPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnPublishRequest.ProtoReflect.Descriptor instead.
func (*UnPublishRequest) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{8}
}

func (x *UnPublishRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *UnPublishRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type ListPublishesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishesRequest) Reset() {
	*x = ListPublishesRequest{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishesRequest) ProtoMessage() {}

func (x *ListPublishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishesRequest.ProtoReflect.Descriptor instead.
func (*ListPublishesRequest) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{9}
}

func (x *ListPublishesRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type ListPublishesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publishes     []*Publish             `protobuf:"bytes,1,rep,name=publishes,proto3" json:"publishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishesResponse) Reset() {
	*x = ListPublishesResponse{}
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishesResponse) ProtoMessage() {}

func (x *ListPublishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publishclient_publishapi_protos_publisher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishesResponse.ProtoReflect.Descriptor instead.
func (*ListPublishesResponse) Descriptor() ([]byte, []int) {
	return file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP(), []int{10}
}

func (x *ListPublishesResponse) GetPublishes() []*Publish {
	if x != nil {
		return x.Publishes
	}
	return nil
}

var File_publishclient_publishapi_protos_publisher_proto protoreflect.FileDescriptor

const file_publishclient_publishapi_protos_publisher_proto_rawDesc = "" +
	"\n" +
	"/publishclient/publishapi/protos/publisher.proto\x12\x06client\"%\n" +
	"\x11ResolveUriRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"?\n" +
	"\x12ResolveUriResponse\x12)\n" +
	"\apublish\x18\x01 \x01(\v2\x0f.client.PublishR\apublish\"\xcc\x01\n" +
	"\aPublish\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x1a\n" +
	"\bobjectId\x18\x02 \x01(\tR\bobjectId\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.client.PublishStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\"\x04\n" +
	"\x02Ok\"O\n" +
	"\x17GetPublishStatusRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x1a\n" +
	"\bobjectId\x18\x02 \x01(\tR\bobjectId\"E\n" +
	"\x18GetPublishStatusResponse\x12)\n" +
	"\apublish\x18\x01 \x01(\v2\x0f.client.PublishR\apublish\"\x90\x01\n" +
	"\x0ePublishRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x1a\n" +
	"\bobjectId\x18\x02 \x01(\tR\bobjectId\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1c\n" +
	"\tbacklinks\x18\x05 \x03(\tR\tbacklinks\"/\n" +
	"\x0fPublishResponse\x12\x1c\n" +
	"\tuploadUrl\x18\x01 \x01(\tR\tuploadUrl\"H\n" +
	"\x10UnPublishRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x1a\n" +
	"\bobjectId\x18\x02 \x01(\tR\bobjectId\"0\n" +
	"\x14ListPublishesRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\"F\n" +
	"\x15ListPublishesResponse\x12-\n" +
	"\tpublishes\x18\x01 \x03(\v2\x0f.client.PublishR\tpublishes*^\n" +
	"\bErrCodes\x12\x0e\n" +
	"\n" +
	"Unexpected\x10\x00\x12\f\n" +
	"\bNotFound\x10\x01\x12\x10\n" +
	"\fAccessDenied\x10\x02\x12\x10\n" +
	"\fUriNotUnique\x10\x03\x12\x10\n" +
	"\vErrorOffset\x10\xcc\b*E\n" +
	"\rPublishStatus\x12\x18\n" +
	"\x14PublishStatusCreated\x10\x00\x12\x1a\n" +
	"\x16PublishStatusPublished\x10\x012\xe7\x02\n" +
	"\fWebPublisher\x12C\n" +
	"\n" +
	"ResolveUri\x12\x19.client.ResolveUriRequest\x1a\x1a.client.ResolveUriResponse\x12U\n" +
	"\x10GetPublishStatus\x12\x1f.client.GetPublishStatusRequest\x1a .client.GetPublishStatusResponse\x12:\n" +
	"\aPublish\x12\x16.client.PublishRequest\x1a\x17.client.PublishResponse\x121\n" +
	"\tUnPublish\x12\x18.client.UnPublishRequest\x1a\n" +
	".client.Ok\x12L\n" +
	"\rListPublishes\x12\x1c.client.ListPublishesRequest\x1a\x1d.client.ListPublishesResponseB\x1aZ\x18publishclient/publishapib\x06proto3"

var (
	file_publishclient_publishapi_protos_publisher_proto_rawDescOnce sync.Once
	file_publishclient_publishapi_protos_publisher_proto_rawDescData []byte
)

func file_publishclient_publishapi_protos_publisher_proto_rawDescGZIP() []byte {
	file_publishclient_publishapi_protos_publisher_proto_rawDescOnce.Do(func() {
		file_publishclient_publishapi_protos_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publishclient_publishapi_protos_publisher_proto_rawDesc), len(file_publishclient_publishapi_protos_publisher_proto_rawDesc)))
	})
	return file_publishclient_publishapi_protos_publisher_proto_rawDescData
}

var file_publishclient_publishapi_protos_publisher_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_publishclient_publishapi_protos_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_publishclient_publishapi_protos_publisher_proto_goTypes = []any{
	(ErrCodes)(0),                    // 0: client.ErrCodes
	(PublishStatus)(0),               // 1: client.PublishStatus
	(*ResolveUriRequest)(nil),        // 2: client.ResolveUriRequest
	(*ResolveUriResponse)(nil),       // 3: client.ResolveUriResponse
	(*Publish)(nil),                  // 4: client.Publish
	(*Ok)(nil),                       // 5: client.Ok
	(*GetPublishStatusRequest)(nil),  // 6: client.GetPublishStatusRequest
	(*GetPublishStatusResponse)(nil), // 7: client.GetPublishStatusResponse
	(*PublishRequest)(nil),           // 8: client.PublishRequest
	(*PublishResponse)(nil),          // 9: client.PublishResponse
	(*UnPublishRequest)(nil),         // 10: client.UnPublishRequest
	(*ListPublishesRequest)(nil),     // 11: client.ListPublishesRequest
	(*ListPublishesResponse)(nil),    // 12: client.ListPublishesResponse
}
var file_publishclient_publishapi_protos_publisher_proto_depIdxs = []int32{
	4,  // 0: client.ResolveUriResponse.publish:type_name -> client.Publish
	1,  // 1: client.Publish.status:type_name -> client.PublishStatus
	4,  // 2: client.GetPublishStatusResponse.publish:type_name -> client.Publish
	4,  // 3: client.ListPublishesResponse.publishes:type_name -> client.Publish
	2,  // 4: client.WebPublisher.ResolveUri:input_type -> client.ResolveUriRequest
	6,  // 5: client.WebPublisher.GetPublishStatus:input_type -> client.GetPublishStatusRequest
	8,  // 6: client.WebPublisher.Publish:input_type -> client.PublishRequest
	10, // 7: client.WebPublisher.UnPublish:input_type -> client.UnPublishRequest
	11, // 8: client.WebPublisher.ListPublishes:input_type -> client.ListPublishesRequest
	3,  // 9: client.WebPublisher.ResolveUri:output_type -> client.ResolveUriResponse
	7,  // 10: client.WebPublisher.GetPublishStatus:output_type -> client.GetPublishStatusResponse
	9,  // 11: client.WebPublisher.Publish:output_type -> client.PublishResponse
	5,  // 12: client.WebPublisher.UnPublish:output_type -> client.Ok
	12, // 13: client.WebPublisher.ListPublishes:output_type -> client.ListPublishesResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_publishclient_publishapi_protos_publisher_proto_init() }
func file_publishclient_publishapi_protos_publisher_proto_init() {
	if File_publishclient_publishapi_protos_publisher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publishclient_publishapi_protos_publisher_proto_rawDesc), len(file_publishclient_publishapi_protos_publisher_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publishclient_publishapi_protos_publisher_proto_goTypes,
		DependencyIndexes: file_publishclient_publishapi_protos_publisher_proto_depIdxs,
		EnumInfos:         file_publishclient_publishapi_protos_publisher_proto_enumTypes,
		MessageInfos:      file_publishclient_publishapi_protos_publisher_proto_msgTypes,
	}.Build()
	File_publishclient_publishapi_protos_publisher_proto = out.File
	file_publishclient_publishapi_protos_publisher_proto_goTypes = nil
	file_publishclient_publishapi_protos_publisher_proto_depIdxs = nil
}
